services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: incidentsim
      POSTGRES_USER: incidentsim
      POSTGRES_PASSWORD: incidentsim
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U incidentsim -d incidentsim"]
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ../services/api
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      FAILURE_MODE: "random_500"   # off | db_slow | redis_down | random_500
      CHAOS_PROBABILITY: "0.30"

      DB_TIMEOUT_S: "0.8"
      DB_STATEMENT_TIMEOUT_MS: "800"

      REDIS_TIMEOUT_S: "0.4"
      REDIS_CB_FAILS: "3"
      REDIS_CB_RESET_S: "10"

      RETRY_ATTEMPTS: "3"
      RETRY_INITIAL_S: "0.1"
      RETRY_MAX_S: "1.5"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ../services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../services/web:/usr/share/nginx/html:ro